Chirp.CLI/SimpleDB/CSVDatabase.cs, Chirp.CLI/SimpleDB/IDatabaseRepository.cs, Chirp.CLI/SimpleDB/SimpleDB.csproj
We have created the SimpleDB classlib, empty IDatabaseRepository- and CSVDatabase class.
=> Simple db creation

.gitignore, src/Chirp.CLI/Program.cs, src/Chirp.CLI/UserInterface.cs, test/ChirpCLI.Tests/Chirp.CLI.Tests.cs, test/ChirpCLI.Tests/ChirpCLITests.csproj, test/ChirpCLI.Tests/Usings.cs
Added several unit tests, testing the UserInterface in the Chirp.CLI. both testing display of cheeps and conversion of UnixTime to DateTime.
=> Test branch UnitTest for Chirp.CLI

.github/workflows/test.yaml, Chrip.sln, src/Chirp.CLI/Program.cs, src/Chirp.CLI/UserInterface.cs, src/WebService/Program.cs, test/Chirp.CSVDB.Tests/IntegrationTests.cs
Changed the workflow, such that it starts a localhost, such that we can test it.
this should be removed, when we get azure up and running, just a temporary fix for testing
=> Workflow test

README.md
=> lecture test

test/ChirpCLI.Tests/E2E.cs
End to end tests added to project.
=> End to end tests added to project.

src/Chirp.SQLite/Chirp.SQLite.csproj, src/Chirp.SQLite/DBFacade.cs
Added EmbeddedFileProvider package
=> added EmbeddedFileProvider, as a nuget package

src/Chirp.Core/ICheepRepository.cs, src/Chirp.Infrastructure/CheepRepository.cs, test/Chirp.RazorPages.Tests/CheepRepositoryTests.cs
Includes changes from createAuthor branch
Closes #54 and partially solves #52 
Added a way to create cheeps
=> Create cheep functions

src/Chirp.Infrastructure/CheepRepository.cs, test/Chirp.RazorPages.Tests/CheepRepositoryTests.cs
There was an error in CheepRepository.cs which prevented the program from compiling. Fixing it broke some of the unit tests however, so this needs further looking into.
=> Debugging to get the program running.

src/Chirp.Core/AuthorDTO.cs, src/Chirp.Core/ICheepRepository.cs, src/Chirp.Infrastructure/CheepRepository.cs, src/Chirp.Infrastructure/DataModel.cs, test/Chirp.RazorPages.Tests/CheepRepositoryTests.cs
Closes #52 
Added AuthorDTO
Updated CheepRepository functions to use AuthorDTO
Added two new ways to find authors by name and/or email
Updated tests
=> Added functions in CheepRepository to search for authors

src/Chirp.Infrastructure/CheepRepository.cs, src/Chirp.Infrastructure/UserNotFoundException.cs, test/Chirp.RazorPages.Tests/CheepRepositoryTests.cs
Throws exception when no user is found in the database using GetAuthor methods in CheepRepository
=> User not found exception

README.md
Updated readme to better fit project state
=> Added description and dependencies

.github/workflows/publish.yaml, .github/workflows/test.yaml, LICENSE, src/Chirp.Core/AuthorDTO.cs, src/Chirp.Core/ICheepRepository.cs, src/Chirp.Infrastructure/CheepRepository.cs, src/Chirp.Infrastructure/DataModel.cs, src/Chirp.Infrastructure/UserNotFoundException.cs, src/Chirp.Web/Chirp.Web.csproj, src/Chirp.Web/Program.cs, src/Chirp.Web/appsettings.json, test/Chirp.RazorPages.Tests/CheepRepositoryTests.cs, test/Chirp.RazorPages.Tests/Chirp.RazorPages.Tests.csproj, test/Chirp.RazorPages.Tests/CustomWebApplicationFactory.cs, test/Chirp.RazorPages.Tests/UnitTest.cs
Removed the localhost, from both workflows and test. 
This should resolve #51 and #76
=> Testing without localhost

.github/workflows/publish.yaml
ClientID + ClientSecret added.
=> test settings added

src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs, src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml
Changed IdentityUser in Register Model
Co-authored-by: Rasmus <rsni@itu.dk>
=> Changed IdentityUser in Register Model

test/Chirp.RazorPages.Tests/CheepRepositoryTests.cs
Added unit tests for the repository methods. (One still needs to be looked at it is currently commented out).
=> Unit tests for repository methods. One still missing.

src/Chirp.Infrastructure/CheepRepository.cs, src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml, src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs, src/Chirp.Web/Pages/Public.cshtml, src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml, src/Chirp.Web/Pages/UserTimeline.cshtml, src/Chirp.Web/Pages/UserTimeline.cshtml.cs, test/Chirp.RazorPages.Tests/CheepRepositoryTests.cs
finally resolves #82 
* Followed the book (ASP .NET Core in Action)
* Added UserName claim
* Added navigation ui
=> Login UI complete with Username

src/Chirp.Web/Pages/UserTimeline.cshtml, src/Chirp.Web/Pages/UserTimeline.cshtml.cs
also added validation for private timeline
=> Added 160 charecter validation for private timeline

src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml, src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs, src/Chirp.Web/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs, src/Chirp.Web/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml, src/Chirp.Web/Areas/Identity/Pages/Account/Manage/_ViewImports.cshtml, src/Chirp.Web/Pages/Public.cshtml, src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml, src/Chirp.Web/Pages/UserTimeline.cshtml, src/Chirp.Web/Program.cs
Getting the correct information from github via claims.
* Email and Name from Github claims
* Using the correct username in UI from github
=> GitHub auth info

src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs, src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml, src/Chirp.Web/Pages/UserTimeline.cshtml.cs
fixed login with github and identity user
=> Fixed login

src/Chirp.Web/wwwroot/css/style.css
=> fixed overflow css in cheeps

src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml, src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml.cs
Made it so it you can actually log in with a local user.
The issue related to how SignInManager.PasswordSignInAsync can take either a user name or a user as input, but not email.
=> Fixing login for real

src/Chirp.Web/Pages/Public.cshtml, src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/UserTimeline.cshtml, src/Chirp.Web/Pages/UserTimeline.cshtml.cs
this works, but is very ugly code wise, if any suggestions i would love to see them 😗
=> added next page to Public and User- timeline

.github/workflows/publish.yaml
Added the playwright download script to publish.
=> ensure playwright is installed, when testing in publish

src/Chirp.Core/ICheepRepository.cs, src/Chirp.Core/INotificationsRepository.cs, src/Chirp.Infrastructure/CheepRepository.cs, src/Chirp.Infrastructure/NotificationRepository.cs, src/Chirp.Web/Pages/Details.cshtml.cs, src/Chirp.Web/Pages/ForgetMe.cshtml.cs, src/Chirp.Web/Pages/UserTimeline.cshtml.cs, src/Chirp.Web/Program.cs
The notifications repository contains methods relating to mentions and notifications, except the creation of which is handle in create cheep in the cheep repository.
=> Made mentions compatible with forget me feature, and added a repository for notifications

src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/UserTimeline.cshtml.cs, src/Chirp.Web/Util.cs
Before issues arouse when adding characters or spaces after a mention, this has been resolved.
=> Fixed the issue of trailing characters

src/Chirp.Core/ICheepRepository.cs, src/Chirp.Infrastructure/CheepRepository.cs, src/Chirp.Web/Pages/AboutMe.cshtml, src/Chirp.Web/Pages/AboutMe.cshtml.cs, src/Chirp.Web/Pages/Public.cshtml, src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/UserTimeline.cshtml, src/Chirp.Web/Pages/UserTimeline.cshtml.cs
* Added previous button
* Added page number in the bottom
=> Button and count

.github/workflows/report.yaml, README.md, docs/report.md
Two changes:
- updated report.md with the required template.
- Added report.yaml; a workflow that converts the .md file to a pdf.
=> Added workflow for generating report pdf.

src/Chirp.Core/IAuthorRepository.cs, src/Chirp.Core/ICheepRepository.cs, src/Chirp.Infrastructure/AuthorRepository.cs, src/Chirp.Infrastructure/CheepRepository.cs, src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/UserTimeline.cshtml.cs, test/Chirp.Infrastructure.Tests/AuthorRepositoryTests.cs
* Moved Follow methods to AuthorRepository.
* Changed return type to List<int>.
* Made some variables type specific, to minimize confusion.
=> Follow cleanup

src/Chirp.Core/IAuthorRepository.cs, src/Chirp.Infrastructure/AuthorRepository.cs, src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/UserTimeline.cshtml.cs, test/Chirp.Infrastructure.Tests/AuthorRepositoryTests.cs, test/Chirp.UI.Tests/UITests.cs
* Added playwright test for follow and unfollow functionality
Together with #137 it closes #94
=> Follow UI test

src/Chirp.Core/IAuthorRepository.cs, src/Chirp.Infrastructure/AuthorRepository.cs, src/Chirp.Web/Pages/Public.cshtml.cs, src/Chirp.Web/Pages/UserTimeline.cshtml.cs, test/Chirp.Infrastructure.Tests/AuthorRepositoryTests.cs
* Refactored many of Follow methods to be less error-prone
* Added unit-tests for follow methods
* Added some comments
Together with https://github.com/ITU-BDSA2024-GROUP12/Chirp/pull/138 it closes https://github.com/ITU-BDSA2024-GROUP12/Chirp/issues/94
=> Follow test

docs/report.md
Mathias <bamj@itu.dk>
Rasmus <rsni@itu.dk>
=> Changed formatting and spelling errors
